/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ball.glb --transform --simplify 
Files: ball.glb [5.15MB] > /Users/knevari/Desktop/Projects/merry-christmas/public/ball-transformed.glb [612.18KB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.christmass_ball_inside_0.geometry} material={materials.inside} position={[0, 1.263, 0.015]} rotation={[-Math.PI / 2, 0, 0]} scale={1.263} />
      <mesh geometry={nodes.christmass_ball_ouline_0.geometry} material={materials.ouline} position={[0, 1.266, 0.014]} rotation={[-Math.PI / 2, 0, 0]} scale={1.266} />
      <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} position={[0, 1.534, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.395} />
    </group>
  )
}

useGLTF.preload('/ball-transformed.glb')
