/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 christmas-ball.glb --transform --simplify 
Files: christmas-ball.glb [6.52MB] > /Users/knevari/Desktop/Projects/merry-christmas/public/christmas-ball-transformed.glb [612.18KB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/christmas-ball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.christmass_ball_inside_0.geometry} material={materials.inside} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.christmass_ball_ouline_0.geometry} material={materials.ouline} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/christmas-ball-transformed.glb')
